### ISSUE TITLE
Updates for Milestone 4 

### ISSUE THREAD

**Issue by nicolebid** [UBC-MDS/DSCI-532_2024_9_solar-savers#109]
Items we can do for Milestone 4. Many of these are formatting or minor improvements. We don't have to do them all, they are just things I thought of when doing the reflection. :)

- [ ] fix the default map so the bottom bar isn't pushed down by the extended whitespace of the map
- [ ] reset the newly added cards and panel comparison, in the case that the user selects everything then reselects a new province
- [ ] highlight/pin the selected region on the map
- [ ] highlight points in selected province
- [ ] include more info in the map tooltip: $/kWh, insolation (kWh/m^2)/description
- [ ] Sort Panel Type by price and/or make it more user friendly
- [ ] put a default empty bar chart to display when no comparison is selected 
- [ ] update legend title kWh/m^2 (Also was the original data daily mean insolation ?) 
- [ ] improve card formatting and titles (Ex: Savings to Financial Savings, and fix the display of the `Difference in Savings`  card) 
- [ ] Align the map in the center and make it a bit bigger to take up more white space. 
- [ ] improve titles (bolded or a better font)
- [ ] improve color scheme (background colors and/or map)
- [ ] add a description (intro and/or improve clarity of use--select location prior to panel comparison) 
- [ ] increase size of panel comparison selection column so the bar chart is aligned better
